FROM openjdk:11-jdk as build
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src
RUN ./mvnw clean install

FROM openjdk:11-jdk
EXPOSE 8080
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
ADD target/metis-social-lending-service-*.jar metis-social-lending-service.jar
ENTRYPOINT ["java","-jar","/metis-social-lending-service.jar"]